---
sources:
  go: true
allowed:
  - mit
  - apache-2.0
  - mpl-2.0
  - bsd-2-clause
  - bsd-3-clause
  - isc
reviewed:
  go:
    - github.com/buildkite/yaml # Apache-2.0
    - github.com/drone/go-scm/**/* # BSD-2-Clause-Patent
    - github.com/kanopy-platform/go-http-middleware/* # Apache-2.0
    - golang.org/x/**/*  # bsd-style
    - google.golang.org/protobuf/**/* # BSD-3-Clause
